In [1]:
import numpy as np

a = np.random.randn(5)
print(a)

[ 2.18275844 -1.14678573  1.49737543 -1.52613861  0.89064962]


In [2]:
print(a.shape)  # rank 1 array

(5,)


In [5]:
print(a.T)

[ 2.18275844 -1.14678573  1.49737543 -1.52613861  0.89064962]


In [6]:
print(np.dot(a,a.T))

11.444040883074841


In [7]:
a = np.random.randn(5,1)
print(a)

[[ 0.9479015 ]
 [ 0.50616902]
 [ 1.88607102]
 [ 0.72886315]
 [-0.31694381]]


In [8]:
print(a.T)

[[ 0.9479015   0.50616902  1.88607102  0.72886315 -0.31694381]]


In [9]:
print(np.dot(a,a.T))

[[ 0.89851725  0.47979838  1.78780954  0.69089047 -0.30043152]
 [ 0.47979838  0.25620708  0.95467073  0.36892795 -0.16042714]
 [ 1.78780954  0.95467073  3.55726387  1.37468765 -0.59777854]
 [ 0.69089047  0.36892795  1.37468765  0.53124149 -0.23100867]
 [-0.30043152 -0.16042714 -0.59777854 -0.23100867  0.10045338]]


NEVER USE A RANK 1 ARRAY
--------

In [16]:
assert(a.shape==(5,1))
a = a.reshape((5,1))